mindmap
  root)Я хочу(
    Создать приложение для компьютера
        Windows
            C#
        macOS
            Swift
        Linux
            C++
        Универсальное
            JavaScript
            C++
    Создать мобильное приложение
        Android
            Kotlin
        iOS
            Swift
        Универсальное
            JavaScript
    Создать сайт
        HTML
        CSS
        Интерактивный
            JavaScript
            Ruby
            Python
    Создать игру
        С крутой графикой и физикой
            C++
        Попроще
            C#
        Для Roblox
            Lua
    Побеждать в олимпиадах
        C++
    Работать с искусственным  интеллектом
        Python
    Программировать роботов и "умную" электронику
        C++
        Python
