---
title: Какой язык программирования выбрать новичку?
config:
  theme: forest
---
mindmap
  root)Я хочу программировать, чтобы...(
    desktop{{Создать приложение для компьютера}}
        windows(Windows)
            **C#**<br>.NET
            ::icon(devicon-csharp-plain)
            :::detailed
        mac(macOS)
            **Swift**
            ::icon(devicon-swift-plain)
        linux(Linux)
            **C++**<br>Qt
            ::icon(devicon-cplusplus-plain)
            :::detailed
        crossplatform(Универсальное<br>Будет работать на любой операционной системе)
        :::detailed
            **JavaScript**<br>Electron
            ::icon(devicon-javascript-plain)
            :::detailed
            **C++**<br>Qt
            ::icon(devicon-cplusplus-plain)
            :::detailed
    mobile{{Создать мобильное приложение}}
        android(Android)
            **Kotlin**
            ::icon(devicon-kotlin-plain)
        ios(iOS)
            **Swift**
            ::icon(devicon-swift-plain)
        crossplatform(Универсальное<br>Будет работать на любом устройстве)
        :::detailed
            **JavaScript**<br>React Native
            ::icon(devicon-javascript-plain)
            :::detailed
    website{{Создать сайт}}
        **HTML**
        ::icon(devicon-html5-plain)
        **CSS**
        ::icon(devicon-css3-plain)
        dynamic("Динамический<br>Например, магазин, социальную сеть или доску объявлений")
        :::detailed
            **JavaScript**<br>React
            ::icon(devicon-javascript-plain)
            :::detailed
            **Ruby**<br>Ruby on Rails
            ::icon(devicon-ruby-plain)
            :::detailed
            **Python**<br>Django
            ::icon(devicon-python-plain)
            :::detailed
    game{{Создать игру}}
        roblox(Для Roblox)
            **Lua**<br>Roblox Studio
            ::icon(devicon-lua-plain)
            :::detailed
        **C#**<br>Unity
        ::icon(devicon-csharp-plain)
        :::detailed
    ai{{Работать с искусственным  интеллектом}}
        **Python**<br>PyTorch
        ::icon(devicon-python-plain)
        :::detailed
    electronics{{Программировать роботов и "умную" электронику}}
        **C++**<br>Arduino
        ::icon(devicon-cplusplus-plain)
        :::detailed
        **Python**<br>MicroPython
        ::icon(devicon-python-plain)
        :::detailed
    competition{{Побеждать в олимпиадах}}
        **C++**
        ::icon(devicon-cplusplus-plain)
