---
title: Какой язык программирования выбрать новичку?
config:
  theme: forest
---
mindmap
  root((Я хочу))
    desktop{{Создать приложение для компьютера}}
        windows(Windows)
            C#
        mac(macOS)
            Swift
        linux(Linux)
            C++
        crossplatform(Универсальное)
            JavaScript
            C++
    mobile{{Создать мобильное приложение}}
        android(Android)
            Kotlin
        ios(iOS)
            Swift
        crossplatform(Универсальное)
            JavaScript
    website{{Создать сайт}}
        HTML
        CSS
        interactive(Интерактивный)
            JavaScript
            Ruby
            Python
    game{{Создать игру}}
        superb(С крутой графикой и физикой)
            C++
        simpler(Попроще)
            C#
        roblox(Для Roblox)
            Lua
    competition{{Побеждать в олимпиадах}}
        C++
    ai{{Работать с искусственным  интеллектом}}
        Python
    electronics{{Программировать роботов и "умную" электронику}}
        C++
        Python
